# My MariaDB
# by peppe8o.com
version: '3'
services:
 fireflyiii:
  image: jc5x/firefly-iii:latest
  volumes:
   - firefly_iii_upload:/var/www/firefly-iii/storage/upload
  env_file: .env
  ports:
   - 8090:8080
  depends_on:
   - fireflyiiidb
 fireflyiiidb:
  build: .
  restart: always
  volumes:
   - firefly_iii_db:/var/lib/mysql

volumes:
 firefly_iii_upload:
 firefly_iii_db:
